import { v4 as uuidv4 } from "uuid";

export const questionsArray = [
    {
        uid: uuidv4(),
        que: "Who is governor of RBI?",
        options: {
            a: "Shaktikanta Das",
            b: "Raghuram Rajan",
            c: "Urjit Patel",
            d: "Duvvuri Subbarao",
        },
        answer: "Shaktikanta Das",
    },
    {
        uid: uuidv4(),
        que: "What is the full form of CAGR?",
        options: {
            a: "Compound Average Growth Rate",
            b: "Cumulative Annual Growth Return",
            c: "Compound Annual Growth Rate",
            d: "Current Asset Growth Ratio",
        },
        answer: "Compound Annual Growth Rate",
    },
    {
        uid: uuidv4(),
        que: "The size of the mutual fund industry in India?",
        options: {
            a: "₹10 trillion",
            b: "₹20 trillion",
            c: "₹70 trillion",
            d: "₹60 trillion",
        },
        answer: "₹70 trillion",
    },
    {
        uid: uuidv4(),
        que: "What is the full form of ULIP?",
        options: {
            a: "Unified Life Investment Plan",
            b: "Unit Linked Insurance Plan",
            c: "Universal Long-term Investment Policy",
            d: "Unit Level Income Plan",
        },
        answer: "Unit Linked Insurance Plan",
    },
    {
        uid: uuidv4(),
        que: "What is the minimum ticket size in PMS?",
        options: {
            a: "₹10 lakh",
            b: "₹25 lakh",
            c: "₹50 lakh",
            d: "₹1 crore",
        },
        answer: "₹50 lakh",
    },
    {
        uid: uuidv4(),
        que: "What is the minimum ticket size in AIF?",
        options: {
            a: "₹25 lakh",
            b: "₹50 lakh",
            c: "₹1 crore",
            d: "₹5 crore",
        },
        answer: "₹1 crore",
    },
    {
        uid: uuidv4(),
        que: "What is GDP?",
        options: {
            a: "Gross Domestic Product",
            b: "General Development Plan",
            c: "Global Domestic Production",
            d: "Growth Development Policy",
        },
        answer: "Gross Domestic Product",
    },
    {
        uid: uuidv4(),
        que: "India is __ largest economy in the world?",
        options: {
            a: "3rd",
            b: "5th",
            c: "7th",
            d: "10th",
        },
        answer: "5th",
    },
    {
        uid: uuidv4(),
        que: "What is India’s population?",
        options: {
            a: "1.2 billion",
            b: "1.3 billion",
            c: "1.4 billion",
            d: "1.5 billion",
        },
        answer: "1.4 billion",
    },
    {
        uid: uuidv4(),
        que: "Which of the following is not part of Nifty 50?",
        options: {
            a: "Reliance Industries",
            b: "TCS",
            c: "HDFC Bank",
            d: "Tesla",
        },
        answer: "Tesla",
    },
    {
        uid: uuidv4(),
        que: "What is SIP, STP & SWP?",
        options: {
            a: "Mutual fund schemes",
            b: "Insurance plans",
            c: "Loan types",
            d: "Credit rating systems",
        },
        answer: "Mutual fund schemes",
    },
    {
        uid: uuidv4(),
        que: "Emergency fund should ideally cover how many months of expenses?",
        options: {
            a: "3 months",
            b: "6 months",
            c: "9 months",
            d: "12 months",
        },
        answer: "6 months",
    },
    {
        uid: uuidv4(),
        que: "Multi Asset Fund invests in which categories?",
        options: {
            a: "Stocks only",
            b: "Bonds only",
            c: "Stocks, Bonds, and Gold",
            d: "Real Estate only",
        },
        answer: "Stocks, Bonds, and Gold",
    },
    {
        uid: uuidv4(),
        que: "What is Expense Ratio?",
        options: {
            a: "Ratio of expenses to profit",
            b: "Fees charged by mutual funds",
            c: "Interest charged by banks",
            d: "Loan repayment ratio",
        },
        answer: "Fees charged by mutual funds",
    },
    {
        uid: uuidv4(),
        que: "What is Exit Load?",
        options: {
            a: "Fee for switching funds",
            b: "Penalty for early withdrawal",
            c: "Management fee",
            d: "Annual maintenance fee",
        },
        answer: "Penalty for early withdrawal",
    },
    {
        uid: uuidv4(),
        que: "What is the primary purpose of insurance?",
        options: {
            a: "To save taxes",
            b: "To earn returns",
            c: "To provide financial protection",
            d: "To invest in stocks",
        },
        answer: "To provide financial protection",
    },
    {
        uid: uuidv4(),
        que: "What is considered a good credit score?",
        options: {
            a: "300-500",
            b: "500-600",
            c: "600-700",
            d: "700-900",
        },
        answer: "700-900",
    },
    {
        uid: uuidv4(),
        que: "Which of these is an appreciating asset?",
        options: {
            a: "Car",
            b: "Gold",
            c: "Mobile phone",
            d: "Clothes",
        },
        answer: "Gold",
    },
    {
        uid: uuidv4(),
        que: "What is Current Ratio?",
        options: {
            a: "Assets divided by liabilities",
            b: "Profit divided by revenue",
            c: "Cash divided by inventory",
            d: "Debt divided by income",
        },
        answer: "Assets divided by liabilities",
    },
    {
        uid: uuidv4(),
        que: "Which of these are liquid assets?",
        options: {
            a: "Real estate",
            b: "Cash and savings",
            c: "Long-term investments",
            d: "Vehicles",
        },
        answer: "Cash and savings",
    },
    {
        uid: uuidv4(),
        que: "What is SGB?",
        options: {
            a: "Sovereign Gold Bonds",
            b: "State Government Bonds",
            c: "Small Growth Bonds",
            d: "Special Government Bonds",
        },
        answer: "Sovereign Gold Bonds",
    },
    {
        uid: uuidv4(),
        que: "Which gives higher returns in the long term?",
        options: {
            a: "Equity",
            b: "Debt",
            c: "FD",
            d: "Bonds",
        },
        answer: "Equity",
    },
    {
        uid: uuidv4(),
        que: "What does RTGS stand for?",
        options: {
            a: "Real Time Gross Settlement",
            b: "Rapid Transfer Grant Scheme",
            c: "Recurring Transaction Gateway System",
            d: "Regional Transfer Group Services",
        },
        answer: "Real Time Gross Settlement",
    },
    {
        uid: uuidv4(),
        que: "What is the governing body of insurance in India?",
        options: {
            a: "SEBI",
            b: "RBI",
            c: "IRDAI",
            d: "NABARD",
        },
        answer: "IRDAI",
    },
    {
        uid: uuidv4(),
        que: "What is the meaning of Maturity Amount in Life Insurance?",
        options: {
            a: "The amount which is paid on death of the Insured person",
            b: "The amount which is paid at the end of the policy period if the Insured person is alive",
            c: "The amount of money paid by the Insured person",
            d: "None of the above",
        },
        answer: "The amount which is paid at the end of the policy period if the Insured person is alive",
    },
];
